name: 'Send Mail'
description: 'Send mail using aliyun dm'
inputs:
  to:  # id of input
    description: 'to'
    required: true
  subject:  # id of input
    description: 'subject'
    required: true
  content:  # id of input
    description: 'content'
    required: true
  sk:  # id of input
    description: 'sk'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
