name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn test
      env:
        INPUT_SK: ${{ secrets.DM_SK }}

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        sk: ${{ secrets.DM_SK }}
        to: woaipingpu@qq.com
        subject: Hello Github Action!
        content: It works in test action.
